name: Sender and Keepalive Workflow

# Schedule this workflow to run daily at 2 PM (UTC)
on:
  schedule:
    - cron: '0 15 * * *'

jobs:
  # Define a job named 'cron'
  cron:
    # Run the job on the latest version of Ubuntu
    runs-on: ubuntu-latest
    # Define the steps for the job
    steps:
      # Checkout the repository code
      - uses: actions/checkout@v2
      # Call an API endpoint to trigger the sender
      - name: Sender API
        run: |
          curl --request GET \
          --url 'https://${{ secrets.MAIN_SITE }}/api/send?key=${{ secrets.TELEGRAM_API_KEY }}'
      # Keep the workflow alive to prevent it from timing out
      - name: Keepalive Workflow
        uses: gautamkrishnar/keepalive-workflow@v1
